### ISSUE TITLE
Help with multi-day forecast.

### ISSUE THREAD

**Issue by daviddelmonte** [MendyK/MKWeatherUndergroundKit#1]
Hi, with a head full of cotton wool, could you please provide an example of an array for a three day forecast, and how to parse such array. I'd be much obliged.. Otherwise, I'd be stomping all over your code.

**Comment by MendyK** [comment]
Thanks for the suggestion. I updated the README with the requested example.

**Comment by daviddelmonte** [comment]
Thanks a ton! Just what I needed. I’d reply on Github but I understand they are weathering a DDOS attack. grrrh.  Again, many thanks. David
On Mar 29, 2015, at 12:31 PM, Mendy Krinsky notifications@github.com wrote:

Thanks for the suggestion. I updated the README with the requested examples.
